### ISSUE TITLE
[META] 🪨 Migration vers NextJS

### ISSUE THREAD

**Issue by bjlaa** [incubateur-ademe/nosgestesclimat-site#1280]
Migration vers une architecture NextJS. Ceci nous permettra d'être plus efficaces sur le plan du SEO et de profiter des nombreuses fonctionnalités avantageuses de NextJS. 

- [x] initialiser le nouveau projet en NextJS
- [x] Migrer les fichiers racine (prettier, netlify, cypress ect)
- [x] Migrer le README
- [x] Migrer index.html
- [x] Migrer la page d'accueil
- [x] Migrer le système de traduction
- [x] Pas mal d'autres trucs

**Comment by jeannelf** [comment]
Update à aujourd'hui, éléments sur lesquels on travaille à ce sprint (27 sept-16 oct) : 

- [ ] #1315 
- [ ] #1319 
- [ ] #1313 
- [ ] #1317 
- [ ] #1316 
- [ ]

**Comment by florianpanchout** [comment]
- [ ] https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1313

**Comment by jeannelf** [comment]
Suite à la recette de cet apres midi : 

Je vous ajoute au fur et a mesure les trucs ici @florianpanchout @bjlaa 

Important
- [ ] #1330 
- [ ] #1329 

Pour plus tard 
- [ ] 
- [ ]
